[package]
name = "rust-test-action"
version = "0.1.0"
authors = ["Sn0wB <51188711+Sn0wB@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"